-- DEMO catalogue only. Review every product before enabling live orders.
insert into public.products(id,slug,data,active,sort_order) values ('sweet-1','kaju-katli','{"id":"sweet-1","slug":"kaju-katli","name":"Kaju Katli","description":"Silky cashew fudge. A little silver, a lot of love.","category":"Nut sweets","image":"/images/sweet-1.webp","gallery":["/images/sweet-1.webp","/images/hero.webp"],"ingredients":["Cashew","Sugar","Ghee"],"allergens":["Nuts","Milk"],"tags":["classic","gifting"],"shelfLife":"7 days","shelfLifeDays":7,"requiresRefrigeration":false,"pieceStock":200,"featured":true,"piecePrice":65,"createdAt":"2026-09-01","variants":[{"id":"sweet-1-0","label":"250 g","price":499,"stock":30},{"id":"sweet-1-1","label":"500 g","price":948,"stock":30},{"id":"sweet-1-2","label":"1 kg","price":1846,"stock":30}]}'::jsonb,true,0) on conflict(id) do update set data=excluded.data;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-1-0','sweet-1','250 g',499,30,0) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-1-1','sweet-1','500 g',948,30,1) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-1-2','sweet-1','1 kg',1846,30,2) on conflict(id) do nothing;
insert into public.inventory(product_id,piece_price,pieces) values ('sweet-1',65,200) on conflict(product_id) do nothing;
insert into public.products(id,slug,data,active,sort_order) values ('sweet-2','motichoor-laddu','{"id":"sweet-2","slug":"motichoor-laddu","name":"Motichoor Laddu","description":"Tiny golden pearls, coming together beautifully.","category":"Classics","image":"/images/sweet-2.webp","gallery":["/images/sweet-2.webp","/images/hero.webp"],"ingredients":["Gram flour","Sugar","Ghee","Cardamom"],"allergens":["Milk","Nuts"],"tags":["classic","festival"],"shelfLife":"5 days","shelfLifeDays":5,"requiresRefrigeration":false,"pieceStock":200,"featured":true,"piecePrice":40,"createdAt":"2026-09-01","variants":[{"id":"sweet-2-0","label":"250 g","price":299,"stock":30},{"id":"sweet-2-1","label":"500 g","price":568,"stock":30},{"id":"sweet-2-2","label":"1 kg","price":1106,"stock":30}]}'::jsonb,true,1) on conflict(id) do update set data=excluded.data;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-2-0','sweet-2','250 g',299,30,0) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-2-1','sweet-2','500 g',568,30,1) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-2-2','sweet-2','1 kg',1106,30,2) on conflict(id) do nothing;
insert into public.inventory(product_id,piece_price,pieces) values ('sweet-2',40,200) on conflict(product_id) do nothing;
insert into public.products(id,slug,data,active,sort_order) values ('sweet-3','narikol-laru','{"id":"sweet-3","slug":"narikol-laru","name":"Narikol Laru","description":"Coconut, slow-stirred into a little taste of home.","category":"Assamese specialties","image":"/images/sweet-3.webp","gallery":["/images/sweet-3.webp","/images/hero.webp"],"ingredients":["Coconut","Sugar","Cardamom"],"allergens":[],"tags":["assam","bihu","vegan"],"shelfLife":"7 days","shelfLifeDays":7,"requiresRefrigeration":false,"pieceStock":200,"featured":true,"piecePrice":35,"createdAt":"2026-09-01","variants":[{"id":"sweet-3-0","label":"250 g","price":249,"stock":30},{"id":"sweet-3-1","label":"500 g","price":473,"stock":30},{"id":"sweet-3-2","label":"1 kg","price":921,"stock":30}]}'::jsonb,true,2) on conflict(id) do update set data=excluded.data;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-3-0','sweet-3','250 g',249,30,0) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-3-1','sweet-3','500 g',473,30,1) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-3-2','sweet-3','1 kg',921,30,2) on conflict(id) do nothing;
insert into public.inventory(product_id,piece_price,pieces) values ('sweet-3',35,200) on conflict(product_id) do nothing;
insert into public.products(id,slug,data,active,sort_order) values ('sweet-4','gulab-jamun','{"id":"sweet-4","slug":"gulab-jamun","name":"Gulab Jamun","description":"Soft milk dumplings in fragrant cardamom syrup.","category":"Milk sweets","image":"/images/sweet-4.webp","gallery":["/images/sweet-4.webp","/images/hero.webp"],"ingredients":["Milk solids","Flour","Sugar","Cardamom"],"allergens":["Milk","Gluten"],"tags":["classic","festival"],"shelfLife":"3 days","shelfLifeDays":3,"requiresRefrigeration":true,"pieceStock":200,"featured":true,"piecePrice":40,"createdAt":"2026-09-01","variants":[{"id":"sweet-4-0","label":"250 g","price":279,"stock":30},{"id":"sweet-4-1","label":"500 g","price":530,"stock":30},{"id":"sweet-4-2","label":"1 kg","price":1032,"stock":30}]}'::jsonb,true,3) on conflict(id) do update set data=excluded.data;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-4-0','sweet-4','250 g',279,30,0) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-4-1','sweet-4','500 g',530,30,1) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-4-2','sweet-4','1 kg',1032,30,2) on conflict(id) do nothing;
insert into public.inventory(product_id,piece_price,pieces) values ('sweet-4',40,200) on conflict(product_id) do nothing;
insert into public.products(id,slug,data,active,sort_order) values ('sweet-5','til-pitha','{"id":"sweet-5","slug":"til-pitha","name":"Til Pitha","description":"Rice flour rolls with a toasted sesame-jaggery heart.","category":"Assamese specialties","image":"/images/sweets-2.webp#0","gallery":["/images/sweets-2.webp#0","/images/hero.webp"],"ingredients":["Rice flour","Black sesame","Jaggery"],"allergens":["Sesame"],"tags":["assam","bihu","vegan"],"shelfLife":"5 days","shelfLifeDays":5,"requiresRefrigeration":false,"pieceStock":200,"featured":false,"piecePrice":40,"createdAt":"2026-09-01","variants":[{"id":"sweet-5-0","label":"250 g","price":299,"stock":30},{"id":"sweet-5-1","label":"500 g","price":568,"stock":30},{"id":"sweet-5-2","label":"1 kg","price":1106,"stock":30}]}'::jsonb,true,4) on conflict(id) do update set data=excluded.data;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-5-0','sweet-5','250 g',299,30,0) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-5-1','sweet-5','500 g',568,30,1) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-5-2','sweet-5','1 kg',1106,30,2) on conflict(id) do nothing;
insert into public.inventory(product_id,piece_price,pieces) values ('sweet-5',40,200) on conflict(product_id) do nothing;
insert into public.products(id,slug,data,active,sort_order) values ('sweet-6','rasgulla','{"id":"sweet-6","slug":"rasgulla","name":"Rasgulla","description":"Cloud-soft chhana, steeped in a delicate sugar syrup.","category":"Milk sweets","image":"/images/sweets-2.webp#1","gallery":["/images/sweets-2.webp#1","/images/hero.webp"],"ingredients":["Milk","Sugar"],"allergens":["Milk"],"tags":["classic"],"shelfLife":"3 days","shelfLifeDays":3,"requiresRefrigeration":true,"pieceStock":200,"featured":false,"piecePrice":35,"createdAt":"2026-09-01","variants":[{"id":"sweet-6-0","label":"250 g","price":249,"stock":30},{"id":"sweet-6-1","label":"500 g","price":473,"stock":30},{"id":"sweet-6-2","label":"1 kg","price":921,"stock":30}]}'::jsonb,true,5) on conflict(id) do update set data=excluded.data;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-6-0','sweet-6','250 g',249,30,0) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-6-1','sweet-6','500 g',473,30,1) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-6-2','sweet-6','1 kg',921,30,2) on conflict(id) do nothing;
insert into public.inventory(product_id,piece_price,pieces) values ('sweet-6',35,200) on conflict(product_id) do nothing;
insert into public.products(id,slug,data,active,sort_order) values ('sweet-7','sandesh','{"id":"sweet-7","slug":"sandesh","name":"Sandesh","description":"Fresh chhana, gently sweetened and hand-shaped.","category":"Milk sweets","image":"/images/sweets-2.webp#2","gallery":["/images/sweets-2.webp#2","/images/hero.webp"],"ingredients":["Milk","Sugar","Cardamom"],"allergens":["Milk"],"tags":["classic"],"shelfLife":"2 days","shelfLifeDays":2,"requiresRefrigeration":true,"pieceStock":200,"featured":false,"piecePrice":45,"createdAt":"2026-09-01","variants":[{"id":"sweet-7-0","label":"250 g","price":349,"stock":30},{"id":"sweet-7-1","label":"500 g","price":663,"stock":30},{"id":"sweet-7-2","label":"1 kg","price":1291,"stock":30}]}'::jsonb,true,6) on conflict(id) do update set data=excluded.data;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-7-0','sweet-7','250 g',349,30,0) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-7-1','sweet-7','500 g',663,30,1) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-7-2','sweet-7','1 kg',1291,30,2) on conflict(id) do nothing;
insert into public.inventory(product_id,piece_price,pieces) values ('sweet-7',45,200) on conflict(product_id) do nothing;
insert into public.products(id,slug,data,active,sort_order) values ('sweet-8','kesar-peda','{"id":"sweet-8","slug":"kesar-peda","name":"Kesar Peda","description":"Slow-reduced milk with a whisper of saffron.","category":"Milk sweets","image":"/images/sweets-2.webp#3","gallery":["/images/sweets-2.webp#3","/images/hero.webp"],"ingredients":["Milk","Sugar","Saffron","Ghee"],"allergens":["Milk"],"tags":["festival"],"shelfLife":"5 days","shelfLifeDays":5,"requiresRefrigeration":true,"pieceStock":200,"featured":false,"piecePrice":45,"createdAt":"2026-09-01","variants":[{"id":"sweet-8-0","label":"250 g","price":349,"stock":30},{"id":"sweet-8-1","label":"500 g","price":663,"stock":30},{"id":"sweet-8-2","label":"1 kg","price":1291,"stock":30}]}'::jsonb,true,7) on conflict(id) do update set data=excluded.data;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-8-0','sweet-8','250 g',349,30,0) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-8-1','sweet-8','500 g',663,30,1) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-8-2','sweet-8','1 kg',1291,30,2) on conflict(id) do nothing;
insert into public.inventory(product_id,piece_price,pieces) values ('sweet-8',45,200) on conflict(product_id) do nothing;
insert into public.products(id,slug,data,active,sort_order) values ('sweet-9','boondi-laddu','{"id":"sweet-9","slug":"boondi-laddu","name":"Boondi Laddu","description":"A generous handful of golden, ghee-kissed boondi.","category":"Classics","image":"/images/sweets-3.webp#0","gallery":["/images/sweets-3.webp#0","/images/hero.webp"],"ingredients":["Gram flour","Sugar","Ghee"],"allergens":["Milk"],"tags":["festival"],"shelfLife":"5 days","shelfLifeDays":5,"requiresRefrigeration":false,"pieceStock":200,"featured":false,"piecePrice":35,"createdAt":"2026-09-01","variants":[{"id":"sweet-9-0","label":"250 g","price":249,"stock":30},{"id":"sweet-9-1","label":"500 g","price":473,"stock":30},{"id":"sweet-9-2","label":"1 kg","price":921,"stock":30}]}'::jsonb,true,8) on conflict(id) do update set data=excluded.data;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-9-0','sweet-9','250 g',249,30,0) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-9-1','sweet-9','500 g',473,30,1) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-9-2','sweet-9','1 kg',921,30,2) on conflict(id) do nothing;
insert into public.inventory(product_id,piece_price,pieces) values ('sweet-9',35,200) on conflict(product_id) do nothing;
insert into public.products(id,slug,data,active,sort_order) values ('sweet-10','chamcham','{"id":"sweet-10","slug":"chamcham","name":"Chamcham","description":"Tender chhana with a delicate coconut finish.","category":"Milk sweets","image":"/images/sweets-3.webp#1","gallery":["/images/sweets-3.webp#1","/images/hero.webp"],"ingredients":["Milk","Sugar","Coconut"],"allergens":["Milk"],"tags":["classic"],"shelfLife":"3 days","shelfLifeDays":3,"requiresRefrigeration":true,"pieceStock":200,"featured":false,"piecePrice":40,"createdAt":"2026-09-01","variants":[{"id":"sweet-10-0","label":"250 g","price":299,"stock":30},{"id":"sweet-10-1","label":"500 g","price":568,"stock":30},{"id":"sweet-10-2","label":"1 kg","price":1106,"stock":30}]}'::jsonb,true,9) on conflict(id) do update set data=excluded.data;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-10-0','sweet-10','250 g',299,30,0) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-10-1','sweet-10','500 g',568,30,1) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-10-2','sweet-10','1 kg',1106,30,2) on conflict(id) do nothing;
insert into public.inventory(product_id,piece_price,pieces) values ('sweet-10',40,200) on conflict(product_id) do nothing;
insert into public.products(id,slug,data,active,sort_order) values ('sweet-11','mysore-pak','{"id":"sweet-11","slug":"mysore-pak","name":"Mysore Pak","description":"Crumbly gram flour and ghee, melting with every bite.","category":"Classics","image":"/images/sweets-3.webp#2","gallery":["/images/sweets-3.webp#2","/images/hero.webp"],"ingredients":["Gram flour","Sugar","Ghee"],"allergens":["Milk"],"tags":["gifting"],"shelfLife":"7 days","shelfLifeDays":7,"requiresRefrigeration":false,"pieceStock":200,"featured":false,"piecePrice":55,"createdAt":"2026-09-01","variants":[{"id":"sweet-11-0","label":"250 g","price":399,"stock":30},{"id":"sweet-11-1","label":"500 g","price":758,"stock":30},{"id":"sweet-11-2","label":"1 kg","price":1476,"stock":30}]}'::jsonb,true,10) on conflict(id) do update set data=excluded.data;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-11-0','sweet-11','250 g',399,30,0) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-11-1','sweet-11','500 g',758,30,1) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-11-2','sweet-11','1 kg',1476,30,2) on conflict(id) do nothing;
insert into public.inventory(product_id,piece_price,pieces) values ('sweet-11',55,200) on conflict(product_id) do nothing;
insert into public.products(id,slug,data,active,sort_order) values ('sweet-12','milk-cake','{"id":"sweet-12","slug":"milk-cake","name":"Milk Cake","description":"Caramelised milk with a beautifully grainy bite.","category":"Milk sweets","image":"/images/sweets-3.webp#3","gallery":["/images/sweets-3.webp#3","/images/hero.webp"],"ingredients":["Milk","Sugar","Ghee"],"allergens":["Milk"],"tags":["classic"],"shelfLife":"5 days","shelfLifeDays":5,"requiresRefrigeration":true,"pieceStock":200,"featured":false,"piecePrice":45,"createdAt":"2026-09-01","variants":[{"id":"sweet-12-0","label":"250 g","price":349,"stock":30},{"id":"sweet-12-1","label":"500 g","price":663,"stock":30},{"id":"sweet-12-2","label":"1 kg","price":1291,"stock":30}]}'::jsonb,true,11) on conflict(id) do update set data=excluded.data;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-12-0','sweet-12','250 g',349,30,0) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-12-1','sweet-12','500 g',663,30,1) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-12-2','sweet-12','1 kg',1291,30,2) on conflict(id) do nothing;
insert into public.inventory(product_id,piece_price,pieces) values ('sweet-12',45,200) on conflict(product_id) do nothing;
insert into public.products(id,slug,data,active,sort_order) values ('sweet-13','kaju-roll','{"id":"sweet-13","slug":"kaju-roll","name":"Kaju Roll","description":"A soft cashew roll with a pistachio centre.","category":"Nut sweets","image":"/images/sweets-4.webp#0","gallery":["/images/sweets-4.webp#0","/images/hero.webp"],"ingredients":["Cashew","Pistachio","Sugar"],"allergens":["Nuts"],"tags":["gifting"],"shelfLife":"7 days","shelfLifeDays":7,"requiresRefrigeration":false,"pieceStock":200,"featured":false,"piecePrice":70,"createdAt":"2026-09-01","variants":[{"id":"sweet-13-0","label":"250 g","price":549,"stock":30},{"id":"sweet-13-1","label":"500 g","price":1043,"stock":30},{"id":"sweet-13-2","label":"1 kg","price":2031,"stock":30}]}'::jsonb,true,12) on conflict(id) do update set data=excluded.data;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-13-0','sweet-13','250 g',549,30,0) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-13-1','sweet-13','500 g',1043,30,1) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-13-2','sweet-13','1 kg',2031,30,2) on conflict(id) do nothing;
insert into public.inventory(product_id,piece_price,pieces) values ('sweet-13',70,200) on conflict(product_id) do nothing;
insert into public.products(id,slug,data,active,sort_order) values ('sweet-14','gur-laru','{"id":"sweet-14","slug":"gur-laru","name":"Gur Laru","description":"A comforting Assamese coconut and jaggery sweet.","category":"Assamese specialties","image":"/images/sweets-4.webp#1","gallery":["/images/sweets-4.webp#1","/images/hero.webp"],"ingredients":["Coconut","Jaggery"],"allergens":[],"tags":["assam","bihu","vegan"],"shelfLife":"7 days","shelfLifeDays":7,"requiresRefrigeration":false,"pieceStock":200,"featured":false,"piecePrice":35,"createdAt":"2026-09-01","variants":[{"id":"sweet-14-0","label":"250 g","price":249,"stock":30},{"id":"sweet-14-1","label":"500 g","price":473,"stock":30},{"id":"sweet-14-2","label":"1 kg","price":921,"stock":30}]}'::jsonb,true,13) on conflict(id) do update set data=excluded.data;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-14-0','sweet-14','250 g',249,30,0) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-14-1','sweet-14','500 g',473,30,1) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-14-2','sweet-14','1 kg',921,30,2) on conflict(id) do nothing;
insert into public.inventory(product_id,piece_price,pieces) values ('sweet-14',35,200) on conflict(product_id) do nothing;
insert into public.products(id,slug,data,active,sort_order) values ('sweet-15','ghila-pitha','{"id":"sweet-15","slug":"ghila-pitha","name":"Ghila Pitha","description":"Golden rice-flour cakes, a familiar Bihu favourite.","category":"Assamese specialties","image":"/images/sweets-4.webp#2","gallery":["/images/sweets-4.webp#2","/images/hero.webp"],"ingredients":["Rice flour","Jaggery","Oil"],"allergens":[],"tags":["assam","bihu","vegan"],"shelfLife":"3 days","shelfLifeDays":3,"requiresRefrigeration":false,"pieceStock":200,"featured":false,"piecePrice":35,"createdAt":"2026-09-01","variants":[{"id":"sweet-15-0","label":"250 g","price":249,"stock":30},{"id":"sweet-15-1","label":"500 g","price":473,"stock":30},{"id":"sweet-15-2","label":"1 kg","price":921,"stock":30}]}'::jsonb,true,14) on conflict(id) do update set data=excluded.data;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-15-0','sweet-15','250 g',249,30,0) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-15-1','sweet-15','500 g',473,30,1) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-15-2','sweet-15','1 kg',921,30,2) on conflict(id) do nothing;
insert into public.inventory(product_id,piece_price,pieces) values ('sweet-15',35,200) on conflict(product_id) do nothing;
insert into public.products(id,slug,data,active,sort_order) values ('sweet-16','premium-mithai-box','{"id":"sweet-16","slug":"premium-mithai-box","name":"Premium Mithai Box","description":"A thoughtful assortment of our signature mithai.","category":"Gift boxes","image":"/images/sweets-5.webp#0","gallery":["/images/sweets-5.webp#0","/images/hero.webp"],"ingredients":["Cashew","Milk","Gram flour","Sugar","Ghee"],"allergens":["Milk","Nuts"],"tags":["gifting","wedding","corporate"],"shelfLife":"3 days","shelfLifeDays":3,"requiresRefrigeration":false,"pieceStock":200,"featured":false,"piecePrice":60,"createdAt":"2026-09-01","variants":[{"id":"sweet-16-0","label":"12 pieces","price":899,"stock":30}]}'::jsonb,true,15) on conflict(id) do update set data=excluded.data;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-16-0','sweet-16','12 pieces',899,30,0) on conflict(id) do nothing;
insert into public.inventory(product_id,piece_price,pieces) values ('sweet-16',60,200) on conflict(product_id) do nothing;
insert into public.products(id,slug,data,active,sort_order) values ('sweet-17','bihu-gift-box','{"id":"sweet-17","slug":"bihu-gift-box","name":"Bihu Gift Box","description":"Pitha and laru, made for sharing new beginnings.","category":"Gift boxes","image":"/images/sweets-5.webp#1","gallery":["/images/sweets-5.webp#1","/images/hero.webp"],"ingredients":["Rice flour","Coconut","Sesame","Jaggery"],"allergens":["Sesame"],"tags":["assam","bihu","festival","gifting"],"shelfLife":"3 days","shelfLifeDays":3,"requiresRefrigeration":false,"pieceStock":200,"featured":false,"piecePrice":55,"createdAt":"2026-09-01","variants":[{"id":"sweet-17-0","label":"12 pieces","price":799,"stock":30}]}'::jsonb,true,16) on conflict(id) do update set data=excluded.data;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-17-0','sweet-17','12 pieces',799,30,0) on conflict(id) do nothing;
insert into public.inventory(product_id,piece_price,pieces) values ('sweet-17',55,200) on conflict(product_id) do nothing;
insert into public.products(id,slug,data,active,sort_order) values ('sweet-18','pistachio-barfi','{"id":"sweet-18","slug":"pistachio-barfi","name":"Pistachio Barfi","description":"Rich pistachio fudge, finished with a gentle crunch.","category":"Nut sweets","image":"/images/sweets-4.webp#3","gallery":["/images/sweets-4.webp#3","/images/hero.webp"],"ingredients":["Pistachio","Milk","Sugar"],"allergens":["Milk","Nuts"],"tags":["gifting"],"shelfLife":"5 days","shelfLifeDays":5,"requiresRefrigeration":false,"pieceStock":200,"featured":false,"piecePrice":75,"createdAt":"2026-09-01","variants":[{"id":"sweet-18-0","label":"250 g","price":599,"stock":30},{"id":"sweet-18-1","label":"500 g","price":1138,"stock":30},{"id":"sweet-18-2","label":"1 kg","price":2216,"stock":30}]}'::jsonb,true,17) on conflict(id) do update set data=excluded.data;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-18-0','sweet-18','250 g',599,30,0) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-18-1','sweet-18','500 g',1138,30,1) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,label,price,stock,sort_order) values ('sweet-18-2','sweet-18','1 kg',2216,30,2) on conflict(id) do nothing;
insert into public.inventory(product_id,piece_price,pieces) values ('sweet-18',75,200) on conflict(product_id) do nothing;
insert into public.coupons(code,percent,max_discount,active) values ('SWEET10',10,200,false) on conflict do nothing;
insert into public.blog_posts(slug,title,body,data,published) values('a-taste-of-bihu','Bihu, and the sweetness of coming home.','In Assam, Bihu brings people together around food, music and the simple pleasure of a shared table. Pitha and laru are familiar companions to these celebrations, with recipes that differ from home to home.

Til pitha wraps a filling of sesame and jaggery in rice flour. Narikol laru brings coconut and sweetness together in a small, hand-shaped bite. Their beauty lies in familiar ingredients and the care of the person making them.

A thoughtful Bihu gift need not be elaborate. Choose a few favourites, write a personal note, and leave a little time to enjoy them together.','{"tag":"CULTURE & CELEBRATION","image":"/images/hero.webp"}'::jsonb,true) on conflict(slug) do nothing;
insert into public.blog_posts(slug,title,body,data,published) values('the-art-of-slow','Good things take their own sweet time.','Some flavours cannot be hurried. Milk thickens slowly. Sugar changes with heat. A careful hand knows when a mixture is ready to leave the pan.

Mithai is as much about texture as sweetness: the fine grain of a milk cake, the delicate crumb of a laddu, the smoothness of cashew fudge. Each asks for a different kind of attention.

That is the spirit behind this collection: familiar sweets, thoughtfully presented, with room for the small details that make sharing them special.','{"tag":"FROM THE KITCHEN","image":"/images/sweet-1.webp"}'::jsonb,true) on conflict(slug) do nothing;
insert into public.blog_posts(slug,title,body,data,published) values('a-thoughtful-gift','A little thought goes a long way.','The best gift starts with the person receiving it. Are they always reaching for the last kaju katli? Do they prefer coconut and jaggery? A small assortment of their favourites says you have been paying attention.

Include a handwritten-style note, consider any allergies, and choose a delivery date that leaves time to enjoy the sweets while they are fresh.

For a larger celebration, get in touch before ordering so the shop can help with quantities, packing and timing.','{"tag":"THE GIFTING EDIT","image":"/images/sweet-3.webp"}'::jsonb,true) on conflict(slug) do nothing;
